# Generated by Django 6.0 on 2026-01-06 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accnum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availble_balance', models.IntegerField(default=0)),
                ('acc_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountnumber', to='transfer_money.account_number')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trans', to='transfer_money.account_number')),
                ('to_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_trans', to='transfer_money.account_number')),
            ],
        ),
    ]
